연립일차방정식은 ax+by+c=0, dx+ey+f=0 의 형태이다, 이때 연립일차방정식의 해를 자동으로 구해주는 프로그램을 만들어라.

연립일차방정식의 풀이법은 가감법과 대입법이 있다. 가감법은 연립일차방정식의 두 일차방정식에 적당한 수를 곱한 후 두 방정식을 빼 한 미지수의 해를 구하고 다른 미지수의 해를 구할 수 있고, 대입법은 예를 들어 y = x + 2같이 연립일차방정식의 한 일차방정식을 적당하게 이항해 만든 후 다른 연립일차방정식의 일차방정식에 대입시켜 한 미지수의 값을 구한 후 다른 미지수 값을 구한다.
(x+2)/5 + (2y+2)/7 = 2/5, x/2 + y/3 = 5같이 a,a',b,b'에 분수가 들어가는 것은 제외시켜도 된다.
해가 특수한 경우는 추가해야 한다.
가감법을 추천드립니다.
문제에 대한 문제가 있는 경우 알려주세요. 수정하겠습니다.

In [33]:
#연립방정식 구하기?
import numpy as np
import re

string = "2x+3y+4=5x+6y-8" #input("ax+by+c=dx +ey+f 기준")
numbers = re.findall("-?\d+", string) # 음수포함 추출기
print(numbers)
numarray = np.asarray(list(map(int, numbers))) 
print(numarray)
leftarray = numarray[0:3]
rightarray = numarray[3:6]
print(leftarray)
print(rightarray)

left2 = rightarray[0] * leftarray
right2 = leftarray * rightarray
y = -right2[1]/left2[1]  
x = (-1 * leftarray[1] * y - c) / a
print(x , y)


['2', '3', '4', '5', '6', '-8']
[ 2  3  4  5  6 -8]
[2 3 4]
[ 5  6 -8]
0.5999999999999996 -1.2


abcdef 다받기
ad를 k로 정하기
k/a를 abc에 곱하고 vartwo 꼴로 만들기 
k/d를 def에 곱하고 똑같이 

b2 - e2가 y고,  c2 - f2가 상수값이니까
a2y + c2 = 0, y = -c2/a2.
ax + by + c = 0꼴에
ax = -by - c
x = -by - c / a



In [17]:
import re

string = input("ax+by+c=dx+ey+f 기준")
numbers = (re.sub(r'[^0-9]', '', string))
numarray = np.asarray(list(map(int, numbers)))    


[3 4 3 7 3 2]
